[package]
name = "lobo-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[features]
testkit = []

[dependencies]
lobo-proto = { path = "../lobo-proto" }
lobo-agent = { path = "../lobo-agent" }
tokio.workspace = true
tokio-util.workspace = true
futures-util.workspace = true
reqwest.workspace = true
async-trait.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono = { workspace = true, features = ["clock"] }
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
hex.workspace = true
sha2.workspace = true
base64.workspace = true
regex-lite.workspace = true
tempfile.workspace = true
rusty-s3.workspace = true
tar.workspace = true
flate2.workspace = true
libc.workspace = true
rand.workspace = true
nix.workspace = true
zip.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
objc2-metal = { version = "0.3.2", default-features = false, features = ["std", "MTLDevice"] }

[dev-dependencies]
wiremock.workspace = true
tokio = { workspace = true, features = ["test-util"] }

[[bin]]
name = "lobo-core-testchild"
path = "src/bin/testchild.rs"
