// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfigShow = { path: string, exists: boolean, values: { [key in string]: string }, set: { [key in string]: boolean }, };
