// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Go's zero time and RFC3339Nano formatting, including the original UTC offset.
 */
export type GoTime = string;
