// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Gpu = { name: string, vram_used_mb: number, vram_total_mb: number, util_pct: number, };
