// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoTime } from "./GoTime";

export type Instance = { provider: string, id: string, status: string, detail: string, cost_per_hr: number, started_at: GoTime, host_download_mbps: number, };
