// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelState } from "./ModelState";
import type { RuntimeInfo } from "./RuntimeInfo";

export type Listing = { weights: string, free_bytes: number, models: Array<ModelState>, runtime: RuntimeInfo, };
