// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Llama = { requests_processing: number, requests_deferred: number, prompt_tokens_total: number, gen_tokens_total: number, prompt_tps: number, gen_tps: number, };
