// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoTime } from "./GoTime";

export type LocalState = { pid: number, port: number, api_port: number, model: string, weights: string, started_at: GoTime, boot_id: string, };
