// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Defaults } from "./Defaults";
import type { GoTime } from "./GoTime";
import type { ModelRef } from "./ModelRef";

export type Manifest = { version: string, git_sha: string, git_dirty: boolean, built_at: GoTime, built_by: string, llama_image: string, model: ModelRef, defaults: Defaults, };
