// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelState = { id: string, file: string, size: number, on_disk: number, verified: boolean, };
