// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Model = { id: string, file: string, sha256: string, alias: string, size: number, chunk_sha: Array<string>, };
