// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Readiness = { exists: boolean, cloud_ready: boolean, ready: boolean, local_supported: boolean, providers: Array<string>, default_provider: string, default_model: string, local_port: number, error: string | null, };
