// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timings } from "./Timings";

export type ReadyInfo = { pod_id: string, provider: string, detail: string, attempts: number, rent_to_container_s: number, host_download_mbps: number, timings?: Timings | null, url: string, version: string, git_sha: string, usd_per_h: number, elapsed_ns: number, };
