// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Manifest } from "./Manifest";

export type Resolved = { manifest: Manifest, zip_key: string, zip_sha256: string, };
