// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoTime } from "./GoTime";
import type { Instance } from "./Instance";
import type { Manifest } from "./Manifest";
import type { Status } from "./Status";

export type Snap = { pod: Instance | null, version: Manifest | null, status: Status | null, down: boolean, at: GoTime, };
