// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Stage = "boot" | "tunnel" | "gpu" | "verify" | "download" | "load" | "ready" | "failed" | "terminating" | "unknown";
