// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadProgress } from "./DownloadProgress";
import type { GoTime } from "./GoTime";
import type { Gpu } from "./Gpu";
import type { Host } from "./Host";
import type { Llama } from "./Llama";
import type { Stage } from "./Stage";
import type { Timings } from "./Timings";

export type Status = { boot_id?: string, stage: Stage, stage_detail: string, download: DownloadProgress, uptime_s: number, idle_s: number, kill_in_s: number, kill_reason: string, expires_at: GoTime, gpu: Gpu | null, host: Host | null, llama: Llama | null, metrics_failures: number, model: string, ctx: number, timings: Timings, };
