// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoTime } from "./GoTime";

export type Timings = { container_started_at: GoTime, bootstrap_apt_s: number, bootstrap_zip_s: number, tunnel_s: number, gpu_check_s: number, download_s: number, download_mbps: number, download_source: string, download_conns: number, verify_s: number, load_s: number, ready_at: GoTime, };
