// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DownloadProgress } from "./DownloadProgress";
import type { ReadyInfo } from "./ReadyInfo";

/**
 * One line of `lobo up --json`. An error string marks a failed operation.
 */
export type UpEvent = { phase: string, detail?: string, download?: DownloadProgress | null, ready?: ReadyInfo | null, done?: boolean, err?: string | null, };
