// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * App overrides. None uses the same config defaults as an unset CLI flag.
 */
export type UpRequest = { provider: string | null, model: string | null, ctx: number | null, source: string | null, cloud: string | null, };
