//! Types shared by the pod API, CLI, local state and desktop app.
//! Compatibility is checked against fixtures generated by the Go implementation.

pub mod agent;
pub mod catalog;
pub mod config;
pub mod control;
pub mod gotime;
pub mod local;
pub mod release;

pub use agent::*;
pub use config::*;
pub use control::*;
pub use gotime::GoTime;
pub use local::*;
pub use release::*;

fn null_as_empty<'de, D, T>(deserializer: D) -> Result<Vec<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    use serde::Deserialize;
    Ok(Option::<Vec<T>>::deserialize(deserializer)?.unwrap_or_default())
}

#[cfg(test)]
mod tests;
#[cfg(test)]
mod testutil;
